### ISSUE TITLE
Стилевые замечания

### ISSUE THREAD

**Issue by sergey-shambir** [JokerSSmile/MiniGame#1]
- глагол set в названии метода обозначает установку свойства объекта (особенно в тех языках, где нет свойств как элемента языка). Значит, методы setPosition, setSize, setBounds класса Wall следует переименовать. Если setBounds выводит bounds из position и size, то лучше сделать его приватным методом и вызывать изнутри класса.
- вместо использования MyGame.WIDTH, MyGame.WIDTH лучше передать эти параметры в конструктор Wall
- в PlayerBox.java неиспользуемый импорт: `import ru.patrushevoleg.minigame.MyGame;`. К слову, почему бы в конструктор PlayerBox не передавать Vector2?

**Comment by JokerSSmile** [comment]
@sergey-shambir Исправил
